# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
            preserve_default=False,
        ),
    ]
